### ISSUE TITLE
Updating Column Names

### ISSUE THREAD

**Issue by ema-rose** [tkravits/BoulderPermitCleanUp#1]
Updating column names in [ExcelCleanUp.py](https://github.com/tkravits/BoulderPermitCleanUp/blob/rebuild/ExcelCleanUp.py) to account for the changed names in the city's permit file.

https://github.com/tkravits/BoulderPermitCleanUp/blob/f5adf545c386d83122fa15a6282f8850d3492d20/ExcelCleanUp.py#L34-L75

**Comment by tkravits** [comment]
Going to close this issue since you were able to resolve it 👍
